apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: ghcr.io/bookmanj/demo-app:83bc08cb69b045ac946099ca9238d61cd7fb022a
        name: demo-app
        ports:
        - containerPort: 8080
